### ISSUE TITLE
total_seconds is missing from flask.helpers on recent flask/python setups

### ISSUE THREAD

**Issue by hexkey** [wgwz/flask-cookie-decode#13]
* flask-cookie-decode version: 0.3.2
* Python version: 3.10.11
* Operating System: Docker/Linux
* Flask: 2.3.2

### Description
It seems on recent flask/python setups the total_seconds is missing from flask.helpers

### What I Did

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/theapp/run.py", line 1, in <module>
    from theapp import create_app
  File "/theapp/theapp/__init__.py", line 42, in <module>
    from flask_cookie_decode import CookieDecode
  File "/usr/local/lib/python3.10/site-packages/flask_cookie_decode/__init__.py", line 19, in <module>
    from .cookie_decode import CookieDecode
  File "/usr/local/lib/python3.10/site-packages/flask_cookie_decode/cookie_decode.py", line 8, in <module>
    from flask.helpers import total_seconds
ImportError: cannot import name 'total_seconds' from 'flask.helpers' (/usr/local/lib/python3.10/site-packages/flask/helpers.py)
```

**Comment by wgwz** [comment]
Thanks for reporting the issue, I will have a look at this soon and try get a fix out.

**Comment by wgwz** [comment]
https://github.com/pallets/flask/blob/4bcd4be6b7d69521115ef695a379361732bcaea6/CHANGES.rst#version-210

> total_seconds is removed, use timedelta.total_seconds instead.

**Comment by hexkey** [comment]
thank you, working nicely
